subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(java_version)
        withSourcesJar()
        withJavadocJar()
    }

    repositories {
        mavenCentral()
    }

    publishing {
        publications {
            register('mavenJava', MavenPublication) {
                from components.java
            }
        }
    }
}
