dependencies {
    compileOnlyApi "org.slf4j:slf4j-api:2.0.7"
    api "org.yaml:snakeyaml:2.3"

    testImplementation platform("org.junit:junit-bom:5.10.3")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}
